name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  find-default-go:
    name: 'Find default go version'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "111" > f1.txt
          echo "222" > f2.txt
          echo "bbb" > /tmp/f
          echo "Hash 0"
          echo ${{ hashFiles('**/*.txt /tmp/f')}}
          echo "111" >> f1.txt
          echo "Hash 1"
          echo ${{ hashFiles('**/*.txt /tmp/f')}}
          echo "bbb" >> /tmp/f
          echo "Hash 2"
          echo ${{ hashFiles('**/*.txt /tmp/f')}}
