name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  v4:
    runs-on: windows-latest
    strategy:
      matrix:
        cache: [false]
        go: [1.20.1]
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@main
        with:
          go-version: ${{ matrix.go }}
          cache: ${{ matrix.cache }}
        name: v4-cache-${{ matrix.cache }}

      - run: |
          find /d/hostedtoolcache/windows/go -name '.completed' || echo 'not completed d:'
          find 'C:\hostedtoolcache\windows\go' -name '.completed' || echo 'not completed c:'
          touch 'C:\hostedtoolcache\windows\go\${{ matrix.go }}\x64\.completed'
          ls -la 'C:\hostedtoolcache\windows\go'
          ls -la 'C:\hostedtoolcache\windows\go\${{ matrix.go }}'
          ls -la 'C:\hostedtoolcache\windows\go\${{ matrix.go }}\x64'
          ls -laH 'C:\hostedtoolcache\windows\go\${{ matrix.go }}\x64'
          ls -la /d/hostedtoolcache/windows/go/1.20.1/x64/
          
        shell: bash
          
        
      - uses: actions/setup-go@main
        with:
          go-version: ${{ matrix.go }}
          cache: ${{ matrix.cache }}
        name: v4-cache-${{ matrix.cache }}-2   
          
