name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        repo: [ulule/loukoum, allegro/marathon-consul, rancher/kontainer-engine]
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache: false

      - name: Get Go cached paths
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - name: get
        run: |
          test -d src && (cd src;go get) || go get

      - name: build
        run: |
          test -d src && (cd src;go build) || go build

      - name: stats
        run: |
          echo 'Build results size(Mb):'
          du -m -s `go env GOCACHE`
          echo 'Dependency results size(Mb):'
          du -m -s `go env MODGOCACHE`

