name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          which tar
        shell: bash
