name: pre-install software in GHA runner

on: [push, workflow_dispatch]

jobs:
  set-env:
    strategy:
      matrix:
        os: [macos-latest]
    env:
      HOME: /home/runner/work/
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@main
        with:
          go-version: 'stable'

  no-env:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo $HOME
      - uses: actions/setup-go@main
        with:
          go-version: 'stable'
