name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  v4:
    runs-on: windows-latest
    strategy:
      matrix:
        cache: [false]
        go: [1.20.1]
        no: [1,2,3,4,5,6,7,8,9,10]
    steps:
      # - uses: actions/checkout@v3
      
      - uses: actions/setup-go@pmain
        with:
          go-version: ${{ matrix.go }}
          cache: ${{ matrix.cache }}
        name: v4-cache-${{ matrix.cache }}
        
      - run: |
          echo $PATH
          which go
          go version
          go env
          
          
