name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  check-4_0:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Setup go
        uses: actions/setup-go@v4.0.0
        
  check-4_1:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: Setup go
        uses: actions/setup-go@v4.1.0
