name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  find-default-go:
    name: 'Find default go version'
    runs-on: windows-latest
    outputs:
      version: ${{ steps.goversion.outputs.version }}
    steps:
      - run: |
          ls -la 'C:\hostedtoolcache\windows\go\'
          version=`go env GOVERSION|sed s/^go//`
          echo "default go version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
        id: goversion
        shell: bash
