name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        cache: [true, false]
        action: [actions/setup-go@v3, actions/setup-go@v4]

    steps:
      - uses: ${{ matrix.action }}
        with:
          go-version: 1.20.5
          cache: ${{ matrix.cache }}
        name: ${{ matrix.action }}-cache-${{ matrix.cache }}

