name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  v4:
    runs-on: windows-latest
    strategy:
      matrix:
        cache: [false]
        go: [1.20.1]
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@main
        with:
          go-version: ${{ matrix.go }}
          cache: ${{ matrix.cache }}
        name: v4-cache-${{ matrix.cache }}

      - run: |
          echo 'd:'
          #find /d/hostedtoolcache/windows/go -name '*.comp*e' || echo 'not completed d:'
          echo 'c:'
          #find 'C:\hostedtoolcache\windows\go' -name '*.comp*' || echo 'not completed c:'
          #touch 'C:\hostedtoolcache\windows\go\${{ matrix.go }}\x64.complete'
          ls -la 'C:\hostedtoolcache\windows\go'
          ls -la 'C:\hostedtoolcache\windows\go\${{ matrix.go }}'
          ls -la 'C:\hostedtoolcache\windows\go\${{ matrix.go }}\x64'
          ls -laH 'C:\hostedtoolcache\windows\go\${{ matrix.go }}\x64'
          ls -la /d/hostedtoolcache/windows/go/1.20.1/x64/

          echo 'const fs = require('fs')' > t.js
          echo 'console.log(fs.existsSync(\'/d/hostedtoolcache/windows/go/${{ matrix.go }}/x64.complete\'))' >> t.js
          echo 'console.log(fs.existsSync(\'/c/hostedtoolcache/windows/go/${{ matrix.go }}/x64.complete\'))' >> t.js
          node t.js
          
        shell: bash
          
        
      - uses: actions/setup-go@main
        with:
          go-version: ${{ matrix.go }}
          cache: ${{ matrix.cache }}
        name: v4-cache-${{ matrix.cache }}-2   
          
