name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: akv-demo/test-setup-go@cache-perf
        with:
          go-version: "1.20.x"
          cache: true

      - name: Run
        run: |
          cd hello
          ls -la
          go run .
