name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.runner }}

    steps:
      # - uses: actions/checkout@v3
      - name: Create dummy files to tar
        run: |
          which unzstd
          mkdir dummy
          echo a > dummy/dummy.1
          echo b > dummy/dummy.2
        shell: bash

      - name: Tar them
        run: |
          tar --posix -vcf /tmp/dummy.tzst  -P --use-compress-program zstd dummy
          ls -la /tmp/dummy.tzst
        shell: bash
        
      - name: Untar them
        run: |
          echo 1 >> dummy/dummy.1
          echo 2 >> dummy/dummy.2
          cat dummy/dummy.1
          cat dummy/dummy.2
          ls -la
          ls -la dummy
          tar -vxf /tmp/dummy.tzst  -P --use-compress-program unzstd
          ls -la
          ls -la dummy
          cat dummy/dummy.1
          cat dummy/dummy.2
        shell: bash
