name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "aaaa"> /tmp/env

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: go.sum /tmp/env

      - run: go build
      
      - run: echo "bbbb"> /tmp/env
    
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: go.sum /tmp/env  

      - run: go build
   
  

