name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  v4:
    runs-on: windows-latest
    strategy:
      matrix:
        cache: [false]
        go: [1.20.1]
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@main
        with:
          go-version: ${{ matrix.go }}
          cache: ${{ matrix.cache }}
        name: v4-cache-${{ matrix.cache }}
        
      - uses: actions/setup-go@main
        with:
          go-version: ${{ matrix.go }}
          cache: ${{ matrix.cache }}
        name: v4-cache-${{ matrix.cache }}-2   
          
