name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  v4:
    runs-on: windows-latest
    steps:
      - run: |
          go version
          go env GOROOT
          
      - uses: actions/setup-go@v4
        with:
          go-version: go1.20.5
