name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  v4:
    runs-on: windows-latest
    steps:
      - run: |
          version=`go env GOVERSION|sed s/^go//`
          echo $version
        shell: bash
          
      - uses: actions/setup-go@v4
        if: ${{ false }}
        with:
          go-version: 1.20.5
