name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
          cache: false

      - name: Run
        run: |
          cd hello
          ls -la
          go build .
