name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  

    steps:
      - uses: actions/checkout@v3
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x 
          cache: false

      - name: run go
        run: |
          env
          echo 'go env GOPATH'
          go env GOPATH
          echo "PATH: $PATH"
          echo "GOROOT: $GOROOT"
          ls -la `which go`
