name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: default go
        run: |
          echo 'ls -la /usr/bin/go'
          ls -la /usr/bin/go
          
      - name: Set up Go 1.16.2
        uses: akv-platform/setup-go@usr-bin-go
        with:
          go-version: '1.16.2'          

      - name: run go
        run: |
          env
          echo 'go env GOPATH'
          go env GOPATH
          echo 'ls -la /home/runner/go/bin'
          ls -la /home/runner/go/bin
          echo 'ls -la /usr/bin/go'
          ls -la /usr/bin/go
          echo "PATH: $PATH"
          echo "GOROOT: $GOROOT"
          ls -la `which go`
