name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:        
  find-default-go:
    name: 'Find default go version'
    runs-on: windows-latest
    outputs:
      version: ${{ steps.goversion.outputs.version }}
    steps:
      - run: |
          version=`go env GOVERSION|sed s/^go//`
          echo "default go version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
        id: goversion
        shell: bash
        
  default-main:
    name: 'Validate if symlink is not created for default go'
    runs-on: windows-latest
    needs: find-default-go
    strategy:
      matrix:
        cache: [false, true]
    steps:

      - name: 'Setup default go, cache: ${{ matrix.cache }}'
        uses: actions/setup-go@main
        with:
          go-version: ${{ needs.find-default-go.outputs.version }}
          cache: ${{ matrix.cache }}

      - run: |
          echo $PATH
          which go
          go version
          go env
        shell: bash
