name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.2'

      - name: Run a multi-line script
        run: |
          echo 'ls -la /home/runner/go/bin'
          ls -la /home/runner/go/bin
          echo 'ls -la /usr/bin/go'
          ls -la /usr/bin/go
          echo "PATH: $PATH"
          echo "GOROOT: $GOROOT"
          ls -la `which go`
