name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  find-default-go:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.step1.outputs.gover }}
    steps:
      - run: |
          version=`go env GOVERSION|sed s/^go//`
          echo "default go version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
        shell: bash
        
  use-default-go:
    runs-on: windows-latest
    steps:
      - run: |
          echo "default go: ${{ needs.find-default-go.outputs.version}}"
        shell: bash

          
          
      - uses: actions/setup-go@v4
        if: ${{ false }}
        with:
          go-version: 1.20.5
