name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: default go
        run: |
          echo 'ls -la /usr/bin/go'
          ls -la /usr/bin/go
          
      - name: Set up Go 1.16.2
        uses: actions/setup-go@main
        with:
          go-version: '1.16.2'          

      - name: run go
        run: |
          env
          echo 'go env GOPATH'
          go env GOPATH
          
