name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  v3:
    runs-on: windows-latest
    if: ${{ false }}
    strategy:
      matrix:
        cache: [true, false]
    steps:
      - uses: actions/checkout@v3
      - uses: akv-platform/setup-go@performance
        with:
          go-version: 1.20.5
          cache: ${{ matrix.cache }}
        name: v3-cache-${{ matrix.cache }}
  v4:
    runs-on: windows-latest
    strategy:
      matrix:
        cache: [false]
    steps:
      - uses: actions/checkout@v3
      
      - uses: akv-platform/setup-go@performance
        with:
          go-version: 1.20.5
          cache: ${{ matrix.cache }}
        name: v4-cache-${{ matrix.cache }}
        
      - run: |
          du -m -s 'D:\hostedtoolcache\windows\go\1.20.5\x64'
          du -m -s 'C:\hostedtoolcache\windows\go\1.20.5\x64'
        shell: bash
        name: Disk usage
        
      - run: |
          echo $PATH
          which go
          go --version
          go env
