name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  find-default-go:
    name: 'Find default go version'
    runs-on: ubuntu-latest
    steps:
      - name: f1
        run: |
          echo "111" > f1.txt
          echo "222" > f2.txt
          echo "bbb" > /tmp/f
      - name: h10
        env:
          h: ${{ hashFiles('**/*.txt') }}
        run: echo "Hash $h"
      - name: h11
        env:
          h: ${{ hashFiles('//tmp/f') }}
        run: echo "Hash $h"
        
      - name: h1
        env:
          h: ${{ hashFiles('{**/*.txt,/tmp/f}') }}
        run: echo "Hash $h"

      - name: f2
        run: |
          echo "111" >> f1.txt
      - name: h2
        env:
          h: ${{ hashFiles('{**/*.txt,/tmp/f}') }}
        run: echo "Hash $h"
        
      - name: f3
        run: |
          echo "bbb" >> /tmp/f
      - name: h3
        env:
          h: ${{ hashFiles('**/*.txt,/tmp/f') }}
        run: echo "Hash $h"

