name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        #        image: [ubuntu-latest, windows-latest, macos-latest, self-hosted]
        image: [ubuntu-latest]
    runs-on: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          uname -o
          set
          echo "imageOS='$ImageOS'"
        shell: bash
