name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.runner }}

    steps:
      # - uses: actions/checkout@v3
      - name: Create dummy files to tar
        run: |
          mkdir dummy
          echo 1 > dummy/dummy.1
          echo 2 > dummy/dummy.2
        shell: bash

      - name: Tar them
        run: |
          tar -vcf /tmp/dummy.tar  -P dummy
          ls -la /tmp/dummy.tar
        shell: bash
        
      - name: Untar them
        run: |
          touch dummy
          touch dummy/dummy.1
          touch dummy/dummy.2
          ls -la
          ls -la dummy
          tar -vxf /tmp/dummy.tar  -P
          ls -la
          ls -la dummy
        shell: bash
