name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache: true

      - name: build
        run: |
          echo 'cache before build'
          du -s $(go env GOCACHE) || echo 'no cache'
          go build -v .
          echo 'cache after build'
          du -s $(go env GOCACHE) || echo 'no cache'
