name: pre-install software in GHA runner

on: [push, workflow_dispatch]
env:
  HOME: /home/runner/work/
jobs:
  view-contexts:
    runs-on: ubuntu-latest
    steps:  
      - name: after setup Golang
        run: go version
